vm_docker

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -5,7 +5,7 @@ on:
     branches: [main]
 
 jobs:
-  deploy:
+  build:
     runs-on: ubuntu-latest
 
     steps:
@@ -26,18 +26,29 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
 
+      - name: Install Docker on the VM (if not already installed)
+        run: |
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
+          chmod 600 ssh_key
+          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@13.201.102.194 << 'EOF'
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sudo sh get-docker.sh
+              sudo usermod -aG docker $USER
+              newgrp docker
+            else
+              echo "Docker already installed."
+            fi
+          EOF
+
       - name: Deploy to the VM
         run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
           chmod 600 ssh_key
-
-          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
-
           ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@13.201.102.194 << EOF
-            docker pull $IMAGE
+            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
             docker stop user_backend || true
             docker rm user_backend || true
-            docker run --name user_backend -d -p 8080:8080 $IMAGE
+            docker run --name user_backend -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
           EOF
-
-          rm -f ssh_key
